---
sidebar: sidebar 
permalink: rn/known_issues.html 
keywords: known issues, issues, bugs, fixes 
summary: Você deve analisar todos os problemas conhecidos da versão atual relacionada à API REST do Astra Control. Os problemas conhecidos identificam problemas que podem impedi-lo de usar o produto com sucesso. 
---
= Problemas conhecidos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você deve analisar todos os problemas conhecidos da versão atual relacionada à API REST do Astra Control. Os problemas conhecidos identificam problemas que podem impedi-lo de usar o produto com sucesso.


NOTE: Não há novos problemas conhecidos com a versão 22,08 da API REST do Astra Control. Os problemas descritos abaixo foram descobertos em versões anteriores e ainda são aplicáveis com a versão atual.



== Nem todos os dispositivos de armazenamento em um nó de armazenamento de back-end são descobertos

Ao emitir uma chamada de API REST para recuperar os dispositivos de storage definidos em um nó de storage, somente os dispositivos Astra Data Store são descobertos. Nem todos os dispositivos são devolvidos.
